### PR TITLE
Update DIPY URL

### PR DESCRIPTION
**Pull request by skoudoro**
This PR update DIPY link to redirect to the new website.

### CODE REVIEW

**Comment by vsoch** [comment]
hey @skoudoro ! The error wasn't your fault - we just needed to update the ruby version. I tried a re-run but it's still using the previous - could you rebase with master to get the updated version?

**Comment by skoudoro** [comment]
Thank you @vsoch! I just rebase it and it seems to be ok now!

**Comment by vsoch** [comment]
I'm taking a look now! Sorry had to run from one computer to another and went afk a minute :)

**Comment by vsoch** [comment]
Looks good! https://135-1283579-gh.circle-artifacts.com/0/nipy.github.com/index.html 

Thanks for the updated link, merging.

**Comment by skoudoro** [comment]
Thank you @vsoch!

**Pull request merged**
