### PR TITLE
[WIP] testing updated site build

### PR DESCRIPTION
**Pull request by vsoch**
This will take a few tries to get right, just ignore until I say otherwise. The original build used a machine base and here I'm trying docker.

### CODE REVIEW

**Comment by vsoch** [comment]
Boum! And there you go. Merging!

**Comment by bcipolli** [comment]
lol when did we decide to drop the whole "community" aspect of "open source community". Do we not do code reviews here?

**Comment by vsoch** [comment]
It was just updating circleci to build with version 2.0, and it worked. I'm happy to revert if you think we need to spend time to discuss this. I figured that there was largely nothing to talk about, and was being considerate of others time. Please revert and start a discussion if you think necessary.

**Comment by bcipolli** [comment]
no need to revert. I'm a process kinda guy, and believe in review in everything. Feel free to ping me on any review.

Appreciate the work as always! Just wanted to say hi and offer my service :) Nothing more.

**Comment by vsoch** [comment]
Ah ok! You know, I thought about it, and now regret that I didn't ping you :) You have my promise that I will next time!

**Comment by bcipolli** [comment]
Always a pleasure to work together, and always an opportunity to learn (and probably, more commonly, request pointers to documentation :P )

**Pull request merged**
