### PR TITLE
DOC: Update the DIPY gitter room URL

### PR DESCRIPTION
**Pull request by jhlegarreta**
Update the DIPY gitter room URL.

Follows the DIPY PR:
https://github.com/dipy/dipy/pull/2171

### CODE REVIEW

**Comment by vsoch** [comment]
Looks like the ruby (sub) version is a moving target. I'll fix this momentarily.

**Comment by jhlegarreta** [comment]
@vsoch looks like the transition took place. Also related to [the comment](https://github.com/nipy/nipy.github.com/pull/57#discussion_r392443887) in PR #57.

I cannot see the report of the CI build failure.

Thanks for taking care of the site.

**Comment by vsoch** [comment]
@jhlegarreta you should be able to integrate changes from master and the build will now pass. But don't take my word for it...

image

**Comment by jhlegarreta** [comment]
Awesome @vsoch ! Thanks.

**Pull request merged**
