### PR TITLE
Add Mindboggle to the project directory.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by matthew-brett** [comment]
Thanks for doing that.

**Comment by binarybottle** [comment]
Thank you, Ariel!  

I would remove "(read the story)" if no link is provided.  Speaking of links, wouldn't it be good to provide a link to each package (dipy, nipype, etc.)?

**Comment by arokem** [comment]
Hi! Added a link to the fuller story - sorry about that! 

All the titles of sections are in fact links!

**Comment by arokem** [comment]
See #7

**Comment by binarybottle** [comment]
Ah -- I was fooled by the dark text.  Perhaps a slightly different hue than the surrounding text or a discrete link icon would make it more obvious.

I am excited -- how do I go about moving the mindboggle github repo to nipy/mindboggle.git and its website (already hosted on github) to nipy.org/mindboggle/?

**Pull request merged**
