### PR TITLE
Blog post about Brainhack Americas

### PR DESCRIPTION
**Pull request by arokem**
And embedded @Garyfallidis talk about dipy.

### CODE REVIEW

**Comment by bcipolli** [comment]
So, what's the right way to preview the updated website? I forgot already lol

**Comment by bcipolli** [comment]
Perhaps add a link to the first mention of Dipy?

**Comment by vsoch** [comment]
Guys, you don't need to do PRs to add posts :)

http://neuroimaging.tumblr.com/post/132031133596/hackathons

Ariel, you are admin, Ben if you want to give me an email I can add you as well

**Comment by bcipolli** [comment]
I think it's a great idea to do PRs for any content. On http://neuwritesd.org/, we find reviewing content to be helpful.

I would say, if nobody responds within 24 hours and it's a rush, then wait... otherwise, I think it helps! :)

**Comment by vsoch** [comment]
For posts - the goal of using tumblr is that anyone can submit content easily, and they don't need to submit PR. Having github usage as a requirement (unfortunately) eliminates a huge chunk of the neuroimaging community. For content on the site outside of posts, PRs are appropriate (for example, to update a page for a project).

**Comment by arokem** [comment]
Yep - that's the one drawback of tumblr - no PRs. But you can always
comment on the content, and we can always go back to edit the content, so
feel free to consider every blog post as though it was a PR.

**Comment by vsoch** [comment]
Exactly.

**Comment by binarybottle** [comment]
What about Tinypress or Hubpress?

**Comment by vsoch** [comment]
@binarybottle - do you have rationale to change it from tumblr? It is working seamlessly with comments, integration to twitter, etc:

This is a much better solution to allow posts from anyone that wants to post (and we approve in the same way as a PR). Please check out the site on tumblr:

neuroimaging.tumblr.com

I think you will like it too! :)

**Comment by bcipolli** [comment]
Sounds good to me. I just hope someone will review my blog posts :)

**Comment by arokem** [comment]
Oh great! When can we expect the first one?

**Comment by bcipolli** [comment]
Around 2 weeks... will present about how I built my [SfN "dynamic poster"](http://cseweb.ucsd.edu/~bcipolli/docs/posters/SfN2015/), which I will cross-post to http://neuwritesd.org/ and http://blogs.plos.org/neuro/ .

Looks like this blog will allow me to embed `iframe` (and so have live demos); the other sites cannot. So I'll be pointing from there to here, for a live version (rather than static images).

**Comment by arokem** [comment]
As long as we are the root node. We usually demand exclusive coverage ;)

**Comment by vsoch** [comment]
I would be happy to review as well :)

**Pull request closed without merging**
