### PR TITLE
Add niwidgets

### PR DESCRIPTION
**Pull request by janfreyberg**
Niwidgets is neuroimaging widgets for jupyter notebook.

I also added a new category since I wasn't sure which to add it to!

### CODE REVIEW

**Comment by janfreyberg** [comment]
Not sure why the CI check is failing - the `jekyll serve` was working fine.

**Comment by vsoch** [comment]
hey @janfreyberg ! I fixed the CI to build again, would you mind rebasing to get the updates? Looking forward to seeing!

**Comment by janfreyberg** [comment]
Done!

**Comment by vsoch** [comment]
Awesome! Github link and link to docs looks good - why did you spell visualization with an s? I'm ok if that was the intention - @arokem when it looks good to you, +1 merge.

**Comment by janfreyberg** [comment]
Because I live in the UK and that's how I was taught it ;) I have no real preference either way, just a reflex to be honest!

**Comment by vsoch** [comment]
haha and this is clear evidence of how unwordly I am :) I think this looks good, so I'm going to merge. Thanks for the addition!

**Pull request merged**
