### PR TITLE
adding Computational Anatomy as a category, for mindboggle and dipy

### PR DESCRIPTION
**Pull request by vsoch**
This will create a new category, Data Curation and Annotation, and move mind boggle to it, as a suggested fix to #47. @satra your feedback appreciated here!

### CODE REVIEW

**Comment by satra** [comment]
@vsoch - i think that's not the right category for mindboggle - just like dipy is under diffusion mri, i think mindboggle should be under anatomical mri. mindboggle does computation of shape metrics on surfaces and volumes.

**Comment by vsoch** [comment]
Should we get rid of Diffusion MRI as a category and use Anatomical for both then?

**Comment by satra** [comment]
How about "Computational Anatomy" as a category and put both in it?

**Comment by vsoch** [comment]
Aye!

**Comment by vsoch** [comment]
Thanks @satra !

**Pull request merged**
