### PR TITLE
Add seo tags

### LINKED ISSUE #35: add seo tags
https://github.com/blog/2162-better-discoverability-for-github-pages-sites

### PR DESCRIPTION
**Pull request by vsoch**
This PR will add the "jekyll-seo-tag" plugin, which adds a tag to the header to render meta data and a json-ld object into each header, (which they say) is good for Google search. This will close #35. For example, here is the Dipy page:

image

here is the base page:

image

It might make a difference, it might not, the plugin was recently [featured on the github blog](https://github.com/blog/2162-better-discoverability-for-github-pages-sites), and I thought wouldn't hurt to add.

### CODE REVIEW

**Comment by arokem** [comment]
As long as my presentation today (https://twitter.com/westbigdatahub/status/730810659315822595) gets the credit for the spike in page-views, I am +1 :-)

**Comment by arokem** [comment]
Also, looks like you need to rebase?

**Comment by vsoch** [comment]
Yeah I saw that, been trying to - I'm not sure what is up with my internet connection / github but it's essentially freezing with every command that I issue. I'm going to try cloning a fresh repo and redoing the PR.

**Comment by vsoch** [comment]
Nice job!! :)

**Pull request closed without merging**
