### PR TITLE
Add a link to why_mindboggle web page.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by binarybottle** [comment]
The code looks good -- I would commit this so that the link is live (on http://nipy.org/project-directory/)!

**Comment by satra** [comment]
@binarybottle - mindboggle has been forked to sitting under nipy.

**Comment by binarybottle** [comment]
Thank you, Satra!  I'm excited to maintain mindboggle within nipy!  Does it make sense for me to maintain binarybottle/mindboggle.git?  How do I make changes to nipy/mindboggle.git?  Do I make pull requests and merge them myself?  How do I move mindboggle.info (on github) to nipy.org/mindboggle/?
So many questions!

**Comment by arokem** [comment]
I took that as confirmation to merge.

**Comment by arokem** [comment]
I'll take the answers to the other questions on the nipy mailing list.

**Pull request merged**
