### PR TITLE
Reorder according to ABC. Add nipy-the-library.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by matthew-brett** [comment]
I don't think ABC makes sense - it means that any library beginning with A, no matter how obscure, will go before a library beginning with Z, no matter how fundamental.   So, it will make the project page less useful.   Can see two options:

* use some metric to order the projects;
* use judgement to order the projects;
* have another page which gives more of an overview.

**Comment by arokem** [comment]
That's three :-)

I am not very good at using my judgement. What metric would you propose to
use? I propose the sum-of-squared-impact, adjusted for code testing:

SSE = (forks**2+stars**+release tags**2) / (loc/tests)

I am afraid people might try to game it, by removing code from their
projects willy nilly.

Another page with an overview would be useful, or potentially an overview
at the top of this page?

**Comment by matthew-brett** [comment]
I just noticed 'Neuroimaing in Python' at the top of the page...

**Comment by arokem** [comment]
I planted many intentional typos, to get people in the habit of submitting PRs on this repo.

**Comment by arokem** [comment]
Thanks - fixed  that.

**Pull request merged**
