### PR TITLE
DOC: Mis-tagged subheader in conduct.html

### PR DESCRIPTION
**Pull request by effigies**
Re-read the CoC in relation to #44 and noticed what I think is probably a typo.

### CODE REVIEW

**Comment by vsoch** [comment]
LGTM

**Comment by arokem** [comment]
I don't think so. The paragraph that follows the bullet points elaborates in more detail. But it still belongs under the overall heading "Be careful in the words that you choose".

**Comment by arokem** [comment]
To be clear, I don't think that conciseness per se deserves to be elevated above other points in that list.

**Comment by effigies** [comment]
Just to note what the original was, prior to #9:

https://github.com/nipy/nipy.github.com/blob/786d6583d68537dcba6e148d166e1ed8756978c8/code-of-conduct/index.md#L42-L56

It looks like a minor transliteration error.

**Comment by arokem** [comment]
I stand corrected.

**Pull request merged**
