### PR TITLE
Add google analytics code

### PR DESCRIPTION
**Pull request by arokem**
This seems like the right place to put this (because the footer gets injected into all the page layouts)

### CODE REVIEW

**Comment by vsoch** [comment]
Agreed. What are your thoughts about having the "UA-####" identifier as a variable in the config? Something like:

      # Custom variables
      version: "1.1.0"
      googleanalytics: "UA-69411900-1"

Then in the footer:

      ga('create', '{{ site.googleanalytics }}', 'auto');

It's unlikely to change, but it might be a good idea to not hard code things. To test this out, I can add the Google Analytics code to our current tumblr page, I'll do that and let you know when it's up!

For Google Analytics, is there an ability to associate with multiple gmail accounts? If others wanted to peek at the traffic and such?

**Comment by GaelVaroquaux** [comment]
> For Google Analytics, is there an ability to associate with multiple gmail
> accounts? If others wanted to peek at the traffic and such?

There is, and I'd love to be added on it :). It can give very useful
info.

**Comment by vsoch** [comment]
ok, I just added to [neuroimaging.tumblr.com](neuroimaging.tumblr.com), also in the footer, if you want to test if it seems to be in working shape.

**Comment by arokem** [comment]
Yeah - hits to the blog seem to be registering. I get two orange points
along the West Coast of the US :-)

**Comment by vsoch** [comment]
One of those is me! I've always wanted to be an orange point :) :small_orange_diamond:

**Comment by arokem** [comment]
Making it a config seems like a fine idea. Will implement. 

I just added @GaelVaroquaux and @vsoch to the people able to view this. Anyone else want access? You need to be registered with the big G.

**Comment by vsoch** [comment]
ok, just tested and working as expected! Eggcellent work!

**Comment by vsoch** [comment]
And once I fix up circle the preview / testing will be very easy to do.

**Pull request merged**
