### PR TITLE
Small fixes to the contribute page

### PR DESCRIPTION
**Pull request by bcipolli**
* Missing quote character meant that reggie was not showing! 😱 
* Link to github did not link to github ...

### CODE REVIEW

**Comment by arokem** [comment]
Oh Reggie, we hardly knew ya! Thanks for doing this.

Do you understand why the build is failing?

**Comment by bcipolli** [comment]
Looks like a ruby build issue:
https://github.com/rvm/rvm/issues/4068

Workaround would be to add the following pipe through `sed`. I can do that if you like:
` curl -sSL https://get.rvm.io | sed -E s/\_rvm\_print\_headline/\_rvm\_version/ |bash -s stable --ruby`

**Comment by arokem** [comment]
If you could, that would be great. Thanks!

**Comment by vsoch** [comment]
hey @bcipolli I fixed the circle build issues. Would you might rebasing with master? Thanks!

**Comment by effigies** [comment]
Should this be merged?

**Comment by vsoch** [comment]
yes, yes it should. I didn't see the fix from @bcipolli, and now it's all green, so good to go I think.

**Pull request merged**
